import pygame

COLS = 28
ROWS = 31
TILE_SIZE = 20

SCREEN_WIDTH = COLS * TILE_SIZE
SCREEN_HEIGHT = ROWS * TILE_SIZE + 40
HUD_HEIGHT = 40
FPS = 60

WALL = 0
DOT = 1
EMPTY = 2
PELLET = 3
GHOST_WALL = 4
GHOST_INTERIOR = 5
GHOST_DOOR = 6
TUNNEL = 7

UP = (0, -1)
DOWN = (0, 1)
LEFT = (-1, 0)
RIGHT = (1, 0)
STOP = (0, 0)

DIR_VECTORS = {pygame.K_UP: UP, pygame.K_DOWN: DOWN, pygame.K_LEFT: LEFT, pygame.K_RIGHT: RIGHT,
               pygame.K_w: UP, pygame.K_s: DOWN, pygame.K_a: LEFT, pygame.K_d: RIGHT}

TILE_MAP = {
    'W': WALL, '.': DOT, ' ': EMPTY, 'O': PELLET,
    'G': GHOST_WALL, 'H': GHOST_INTERIOR, 'D': GHOST_DOOR, 'T': TUNNEL,
}

LAYOUT = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W............WW............W",
    "W.WWWW..WWWW.WW.WWWW..WWWW.W",
    "WO.WWW..WWWW.WW.WWWW..WWW.OW",
    "W..........................W",
    "W.WWWW.WW.WWWWWWWW.WW.WWWW.W",
    "W.WWWW.WW.WWWWWWWW.WW.WWWW.W",
    "W......WW....WW....WW......W",
    "WWWWWW.WWWWW.WW.WWWWW.WWWWWW",
    "WWWWWW.WWWWW.WW.WWWWW.WWWWWW",
    "WWWWWW.WW..GGGGGG..WW.WWWWWW",
    "WWWWWW.WW..GHHHHG..WW.WWWWWW",
    "WWWWWW.WW..GHDDHG..WW.WWWWWW",
    "TTTTTT..........TTTTTTTTTTTT",
    "WWWWWW.WW.WWWWWWWW.WW.WWWWWW",
    "WWWWWW.WW.WWWWWWWW.WW.WWWWWW",
    "WWWWWW.WW..........WW.WWWWWW",
    "WWWWWW.WW.WWWWWWWW.WW.WWWWWW",
    "WWWWWW.WW.WWWWWWWW.WW.WWWWWW",
    "W............WW............W",
    "W.WWWW..WWWW.WW.WWWW..WWWW.W",
    "W.WWWW..WWWW.WW.WWWW..WWWW.W",
    "WO..WW.....      .....WW..OW",
    "WWW.WW.WWWWWWWWWW.WW.WWWWWWW",
    "WWW.WW.WWWWWWWWWW.WW.WWWWWWW",
    "W......WW....WW....WW......W",
    "W..WWWWWWWWW.WW.WWWWWWWWW..W",
    "W..WWWWWWWWW.WW.WWWWWWWWW..W",
    "W..........................W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
]

BLACK = (0, 0, 0)
BLUE = (0, 0, 255)
WHITE = (255, 255, 255)
YELLOW = (255, 255, 0)
RED = (255, 0, 0)
PINK = (255, 182, 255)
CYAN = (0, 255, 255)
ORANGE = (255, 182, 85)
DARK_BLUE = (0, 0, 128)
DOT_COLOR = (255, 183, 174)

PLAYER_SPEED = 3
GHOST_SPEED = 2
GHOST_FRIGHTENED_SPEED = 1
GHOST_EATEN_SPEED = 4
PELLET_DURATION = 360
GHOST_START_DELAY = 180

DOT_SCORE = 10
PELLET_SCORE = 50
GHOST_SCORE_BASE = 200
EXTRA_LIFE_SCORE = 10000

LEVEL_SPEED_INCREASE = 1.05
LEVEL_PELLET_DECREASE = 30
MIN_PELLET_DURATION = 60
LEVEL_SCATTER_DECREASE = 30
MIN_SCATTER_DURATION = 60

INITIAL_SCATTER_DURATION = 420
INITIAL_CHASE_DURATION = 1200

HIGH_SCORE_FILE = "pacman.high"
